Repository wanted-team2/2week_Chat, pull requests merged in 2022-02, with the labels that each got.

#6 :wrench: Config: sass loader 추가 in overrides
  config-overrides.js
  package.json
  src/styles/index.scss
  yarn.lock
Labels: config

#7 :sparkles: Feat: Profile 컴포넌트 구현
  src/App.tsx
  src/components/Test/Style.scss
  src/components/Test/Test.tsx
  src/components/base/Profile/Profile.tsx
  src/components/base/Profile/Style.scss
  src/components/base/index.ts
  src/styles/constants/_sizes.scss
  src/styles/constants/size.ts
Labels: Feat

#9 Feat: Login 페이지 구현, useInput 훅 구현, flexbox fd props 추가, route 설정
  package.json
  src/App.tsx
  src/hooks/index.ts
  src/hooks/useInput.ts
  src/pages/Chats/Chats.tsx
  src/pages/Chats/Style.scss
  src/pages/Login/Login.tsx
  src/pages/Login/Style.scss
  src/pages/index.ts
  src/styles/constants/_sizes.scss
  src/styles/mixins/_flexbox.scss
  yarn.lock
Labels: Feat

#12 :sparkles: (Feat: Button, Buttons 구현)
  src/components/base/Button/Button.tsx
  src/components/base/Button/Style.scss
  src/components/base/Buttons/Buttons.tsx
  src/components/base/Buttons/Style.scss
  src/components/base/index.ts
Labels: Feat

#10 ✨ Feat: ChatInput 컴포넌트 구현
  config-overrides.js
  src/App.tsx
  src/components/base/ChatInput/ChatInput.tsx
  src/components/base/ChatInput/Style.scss
  src/components/base/SubmitButton/Style.scss
  src/components/base/SubmitButton/SubmitButton.tsx
  src/components/base/index.ts
  src/components/domain/ChatContainer/ChatContainer.tsx
  src/components/domain/ChatContainer/Style.scss
  src/styles/_globalStyles.scss
  src/styles/constants/_colors.scss
  src/styles/index.scss
  src/types/EventTypes.ts
  tsconfig.paths.json
Labels: Feat, Fix

#19 ✨ Feat: ReplyBox 구현
  src/components/base/ReplyBox/ReplyBox.tsx
  src/components/base/ReplyBox/Style.scss
  src/components/base/index.ts
Labels: Feat, UI

#17 ✨ Feat: Chats 페이지 컴포넌트 구현
  src/components/base/Button/Style.scss
  src/components/base/Buttons/Buttons.tsx
  src/components/domain/MessagesBox/MessagesBox.tsx
  src/components/domain/MessagesBox/Style.scss
  src/components/domain/index.ts
  src/models/MessageData.ts
  src/pages/Chats/Chats.tsx
  src/pages/Chats/Style.scss
  src/styles/_reset.scss
  src/styles/index.scss
Labels: Feat, UI

#22 UI, Feat: 전체 레이아웃 수정, getFormattedDate 함수 적용 in MessagesBox
  src/components/base/Button/Style.scss
  src/components/base/ChatInput/Style.scss
  src/components/base/SubmitButton/Style.scss
  src/components/domain/ChatContainer/Style.scss
  src/components/domain/MessagesBox/MessagesBox.tsx
  src/components/domain/MessagesBox/Style.scss
  src/pages/Chats/Chats.tsx
  src/types/MessageData.ts
  src/utils/functions.ts
Labels: Feat, UI

#27 Feat, UI, Fix: 채팅 스크롤 하단 고정, useModal 훅 이동, height 100vh 적용
  config-overrides.js
  src/components/base/ChatInput/ChatInput.tsx
  src/components/base/ReplyBox/ReplyBox.tsx
  src/components/domain/MessagesBox/MessagesBox.tsx
  src/components/domain/MessagesBox/Style.scss
  src/hooks/index.ts
  src/hooks/useModal.ts
  src/hooks/useScrollToBottom.ts
  src/models/EventTypes.ts
  src/models/MessageData.ts
  src/pages/Chats/Chats.tsx
  src/pages/Chats/Style.scss
  src/redux/actions/chatActions.ts
  src/redux/reducers/chat.ts
  src/styles/_globalStyles.scss
  src/types/index.ts
  src/utils/functions.ts
  tsconfig.paths.json
Labels: Feat, Fix, UI

#31 :lipstick: UI: 개행 처리 in message
  src/components/domain/MessagesBox/MessagesBox.tsx
  src/components/domain/MessagesBox/Style.scss
Labels: UI

#32 Fix, UI: input 컴포넌트 사라지는 오류 해결 in 모바일, Login input 사이즈 수정
  config-overrides.js
  src/pages/Chats/Style.scss
  src/pages/Login/Style.scss
  src/styles/constants/_breakpoints.scss
  src/styles/mixins/_responsive.scss
Labels: Fix, UI

#33 :sparkles: Feat: Login input Validation 추가
  src/pages/Login/Login.tsx
Labels: Feat
